Repository Duckmelang/BE, pull requests merged in 2025-07, with the labels that each got.

#205 [Feat] 자체 회원가입/로그인 API 수정 및 구현
  src/main/java/umc/duckmelang/domain/auth/client/GoogleApiClient.java
  src/main/java/umc/duckmelang/domain/auth/client/KakaoApiClient.java
  src/main/java/umc/duckmelang/domain/auth/client/NaverApiClient.java
  src/main/java/umc/duckmelang/domain/auth/controller/AuthRestController.java
  src/main/java/umc/duckmelang/domain/auth/dto/google/GoogleTokenResponse.java
  src/main/java/umc/duckmelang/domain/auth/dto/google/GoogleUserInfoResponse.java
  src/main/java/umc/duckmelang/domain/auth/dto/kakao/KakaoAccount.java
  src/main/java/umc/duckmelang/domain/auth/dto/kakao/KakaoTokenResponse.java
  src/main/java/umc/duckmelang/domain/auth/dto/kakao/KakaoUserInfoResponse.java
  src/main/java/umc/duckmelang/domain/auth/dto/naver/NaverTokenResponse.java
  src/main/java/umc/duckmelang/domain/auth/dto/naver/NaverUserInfoResponse.java
  src/main/java/umc/duckmelang/domain/auth/dto/request/LoginRequest.java
  src/main/java/umc/duckmelang/domain/auth/dto/request/ResetPasswordRequest.java
  src/main/java/umc/duckmelang/domain/auth/dto/response/CheckIdResponse.java
  src/main/java/umc/duckmelang/domain/auth/dto/response/LoginIdResponse.java
  src/main/java/umc/duckmelang/domain/auth/dto/response/PhoneNumResponse.java
  src/main/java/umc/duckmelang/domain/auth/service/AuthService.java
  src/main/java/umc/duckmelang/domain/auth/service/SocialService.java
  src/main/java/umc/duckmelang/domain/auth/service/strategy/GoogleLoginStrategy.java
  src/main/java/umc/duckmelang/domain/auth/service/strategy/KakaoLoginStrategy.java
  src/main/java/umc/duckmelang/domain/auth/service/strategy/NaverLoginStrategy.java
  src/main/java/umc/duckmelang/domain/auth/service/strategy/SocialLoginStrategy.java
  src/main/java/umc/duckmelang/domain/auth/user/CustomUserDetailsService.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/domain/enums/LoginType.java
  src/main/java/umc/duckmelang/domain/member/dto/member/MemberSignUpDto.java
  src/main/java/umc/duckmelang/domain/member/repository/MemberRepository.java
  src/main/java/umc/duckmelang/domain/member/service/member/MemberCommandServiceImpl.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
Labels: :sparkles: feature, :recycle: refactor

#208 Feature/#206
  src/main/java/umc/duckmelang/domain/admin/controller/AdminRestController.java
  src/main/java/umc/duckmelang/domain/admin/converter/AdminConverter.java
  src/main/java/umc/duckmelang/domain/admin/dto/AdminResponseDto.java
  src/main/java/umc/duckmelang/domain/admin/service/AdminCommandService.java
  src/main/java/umc/duckmelang/domain/admin/service/AdminCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/admin/service/AdminQueryService.java
  src/main/java/umc/duckmelang/domain/admin/service/AdminQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/repository/MemberRepository.java
  src/main/java/umc/duckmelang/global/config/RedissonConfig.java
Labels: :sparkles: feature

#218 [!HOTFIX] 지뢰 키워드 미설정 시 프로필 설정 완료가 되지 않는 문제 해결
  src/main/java/umc/duckmelang/domain/member/service/member/MemberCommandServiceImpl.java
Labels: :bug: bug
