Repository Duckmelang/BE, pull requests merged in 2025-02, with the labels that each got.

#45 Feature/#38
  src/main/java/umc/duckmelang/domain/application/controller/ApplicationRestController.java
  src/main/java/umc/duckmelang/domain/application/converter/ApplicationConverter.java
  src/main/java/umc/duckmelang/domain/application/dto/ReceivedApplicationDto.java
  src/main/java/umc/duckmelang/domain/application/dto/SentApplicationDto.java
  src/main/java/umc/duckmelang/domain/application/repository/ApplicationRepository.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryService.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryServiceImpl.java
  src/main/java/umc/duckmelang/global/security/config/SecurityConfig.java
Labels: duplicate

#61 Feature/#60
  src/main/java/umc/duckmelang/DuckmelangApplication.java
  src/main/java/umc/duckmelang/domain/application/controller/ApplicationRestController.java
  src/main/java/umc/duckmelang/domain/application/converter/ApplicationConverter.java
  src/main/java/umc/duckmelang/domain/application/dto/ApplicationResponseDto.java
  src/main/java/umc/duckmelang/domain/application/dto/SentApplicationDto.java
  src/main/java/umc/duckmelang/domain/application/dto/ShowApplicationDto.java
  src/main/java/umc/duckmelang/domain/application/facade/ApplicationFacadeService.java
  src/main/java/umc/duckmelang/domain/application/repository/ApplicationRepository.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryService.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/domain/MemberProfileImage.java
  src/main/java/umc/duckmelang/domain/postidol/domain/PostIdol.java
  src/main/java/umc/duckmelang/domain/postimage/converter/PostImageConverter.java
  src/main/java/umc/duckmelang/domain/postimage/repository/PostImageRepository.java
  src/main/java/umc/duckmelang/domain/postimage/service/PostImageQueryService.java
  src/main/java/umc/duckmelang/domain/postimage/service/PostImageQueryServiceImpl.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/PostImageException.java
Labels: duplicate

#63 feature/#62
  src/main/java/umc/duckmelang/domain/eventcategory/domain/EventCategory.java
  src/main/java/umc/duckmelang/domain/eventcategory/domain/enums/EventKind.java
Labels: :sparkles: feature

#65 Feature/#40
  src/main/java/umc/duckmelang/domain/application/dto/ApplicationRequestDto.java
  src/main/java/umc/duckmelang/domain/auth/controller/AuthRestController.java
  src/main/java/umc/duckmelang/domain/auth/sms/controller/SmsRestController.java
  src/main/java/umc/duckmelang/domain/auth/sms/repository/SmsRepository.java
  src/main/java/umc/duckmelang/domain/auth/sms/service/SmsService.java
  src/main/java/umc/duckmelang/domain/auth/sms/service/SmsServiceImpl.java
  src/main/java/umc/duckmelang/domain/auth/sms/util/SmsCertificationUtil.java
  src/main/java/umc/duckmelang/domain/member/controller/MemberRestController.java
  src/main/java/umc/duckmelang/domain/member/controller/MyPageRestController.java
  src/main/java/umc/duckmelang/domain/member/controller/ProfileRestController.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberProfileConverter.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/domain/enums/Gender.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberRequestDto.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberResponseDto.java
  src/main/java/umc/duckmelang/domain/member/facade/ProfileFacadeService.java
  src/main/java/umc/duckmelang/domain/member/repository/MemberRepository.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/validation/annotation/ExistMember.java
  src/main/java/umc/duckmelang/domain/member/validation/validator/MemberExistValidator.java
  src/main/java/umc/duckmelang/domain/member/validation/validator/MemberExistsValidator.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/controller/MemberProfileImageController.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageRequestDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/controller/PostRestController.java
  src/main/java/umc/duckmelang/domain/post/converter/PostConverter.java
  src/main/java/umc/duckmelang/domain/post/dto/PostResponseDto.java
  src/main/java/umc/duckmelang/domain/review/controller/ReviewRestController.java
  src/main/java/umc/duckmelang/domain/review/converter/ReviewConverter.java
  src/main/java/umc/duckmelang/domain/review/dto/ReviewResponseDto.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#67 Feature/#66
  build.gradle
  src/main/java/umc/duckmelang/domain/chatmessage/domain/ChatMessage.java
  src/main/java/umc/duckmelang/domain/chatmessage/repository/ChatMessageRepository.java
  src/main/java/umc/duckmelang/domain/chatroom/domain/ChatRoom.java
  src/test/java/umc.duckmelang/DuckmelangApplicationTests.java
  src/test/java/umc.duckmelang/domain/chatmessage/ChatMessageRepositoryTest.java
Labels: :sparkles: feature

#55 Feature/#54
  src/main/java/umc/duckmelang/domain/notification/domain/Notification.java
  src/main/java/umc/duckmelang/domain/notification/domain/enums/NotificationType.java
  src/main/java/umc/duckmelang/domain/notificationsetting/domain/NotificationSetting.java
Labels: :sparkles: feature

#73 Feature/#68
  build.gradle
  src/main/java/umc/duckmelang/global/websocket/WebSocketChatHandler.java
  src/main/java/umc/duckmelang/global/websocket/WebSocketConfig.java
Labels: :sparkles: feature

#69 Feature/#64
  build.gradle
  src/main/java/umc/duckmelang/domain/member/controller/MemberRestController.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberRequestDto.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/controller/MemberProfileImageController.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/converter/MemberProfileImageConverter.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageRequestDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandService.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/controller/PostRestController.java
  src/main/java/umc/duckmelang/domain/post/dto/PostRequestDto.java
  src/main/java/umc/duckmelang/domain/post/dto/PostResponseDto.java
  src/main/java/umc/duckmelang/domain/post/service/PostCommandService.java
  src/main/java/umc/duckmelang/domain/post/service/PostCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/postimage/converter/PostImageConverter.java
  src/main/java/umc/duckmelang/domain/postimage/dto/PostImageRequestDto.java
  src/main/java/umc/duckmelang/domain/uuid/domain/Uuid.java
  src/main/java/umc/duckmelang/domain/uuid/repository/UuidRepository.java
  src/main/java/umc/duckmelang/global/aws/AmazonS3Manager.java
  src/main/java/umc/duckmelang/global/config/AmazonConfig.java
  src/main/java/umc/duckmelang/global/multipart/MultipartJackson2HttpMessageConverter.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#77 Feature/#75
  build.gradle
  src/main/java/umc/duckmelang/domain/chatmessage/domain/ChatMessage.java
  src/main/java/umc/duckmelang/global/common/BaseEntity.java
  src/main/java/umc/duckmelang/global/common/serializer/LocalDateTimeSerializer.java
  src/main/java/umc/duckmelang/global/config/JacksonConfig.java
Labels: :recycle: refactor

#86 Feature/#76
  src/main/java/umc/duckmelang/domain/chatmessage/controller/ChatMessageWebSocketController.java
  src/main/java/umc/duckmelang/domain/chatmessage/converter/ChatMessageConverter.java
  src/main/java/umc/duckmelang/domain/chatmessage/dto/ChatMessageRequestDto.java
  src/main/java/umc/duckmelang/domain/chatmessage/dto/ChatMessageResponseDto.java
  src/main/java/umc/duckmelang/domain/chatmessage/service/ChatMessageCommandService.java
  src/main/java/umc/duckmelang/domain/chatmessage/service/ChatMessageCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/chatmessage/service/ChatMessageQueryService.java
  src/main/java/umc/duckmelang/domain/chatmessage/service/ChatMessageQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/chatroom/converter/ChatRoomConverter.java
  src/main/java/umc/duckmelang/domain/chatroom/domain/ChatRoom.java
  src/main/java/umc/duckmelang/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/umc/duckmelang/domain/chatroom/service/ChatRoomCommandService.java
  src/main/java/umc/duckmelang/domain/chatroom/service/ChatRoomCommandServiceImpl.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/ChatMessageException.java
  src/main/java/umc/duckmelang/global/config/JacksonConfig.java
  src/main/java/umc/duckmelang/global/websocket/WebSocketChatHandler.java
Labels: :sparkles: feature

#87 Feature/#74
  src/main/java/umc/duckmelang/domain/bookmark/service/BookmarkCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/notification/controller/NotificationController.java
  src/main/java/umc/duckmelang/domain/notification/converter/NotificationConverter.java
  src/main/java/umc/duckmelang/domain/notification/domain/Notification.java
  src/main/java/umc/duckmelang/domain/notification/dto/NotificationResponseDto.java
  src/main/java/umc/duckmelang/domain/notification/repository/EmitterRepository.java
  src/main/java/umc/duckmelang/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/umc/duckmelang/domain/notification/repository/NotificationRepository.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationCommandService.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationQueryService.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/review/domain/Review.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewCommandServiceImpl.java
Labels: :sparkles: feature

#101 [feature/#85] 게시글 필터링 관련 API 구현
  src/main/java/umc/duckmelang/domain/application/controller/ApplicationRestController.java
  src/main/java/umc/duckmelang/domain/auth/domain/Auth.java
  src/main/java/umc/duckmelang/domain/auth/domain/enums/ProviderKind.java
  src/main/java/umc/duckmelang/domain/auth/enums/ProviderKind.java
  src/main/java/umc/duckmelang/domain/auth/oauth/CustomOAuth2UserService.java
  src/main/java/umc/duckmelang/domain/auth/repository/AuthRepository.java
  src/main/java/umc/duckmelang/domain/bookmark/controller/BookmarkRestController.java
  src/main/java/umc/duckmelang/domain/member/controller/MemberFilterRestController.java
  src/main/java/umc/duckmelang/domain/member/controller/MyPageRestController.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberFilterConverter.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberFilterDto.java
  src/main/java/umc/duckmelang/domain/member/facade/ProfileFacadeService.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageCommandService.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageQueryService.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/controller/MemberProfileImageRestController.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/converter/MemberProfileImageConverter.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/domain/MemberProfileImage.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageRequestDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/repository/MemberProfileImageRepository.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandService.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryService.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/controller/PostRestController.java
  src/main/java/umc/duckmelang/domain/post/converter/PostConverter.java
  src/main/java/umc/duckmelang/domain/post/repository/PostRepository.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryService.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/review/controller/ReviewRestController.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/common/BaseEntity.java
  src/main/java/umc/duckmelang/global/config/RedisConfig.java
  src/main/java/umc/duckmelang/global/config/SecurityConfig.java
  src/main/java/umc/duckmelang/global/validation/annotation/ExistsApplication.java
  src/main/java/umc/duckmelang/global/validation/validator/ApplicationExistsValidator.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#107 feature/#100 채팅 메세지에 파일, 사진, 링크 첨부 기능 추가
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/aws/AmazonS3Manager.java
  src/main/java/umc/duckmelang/global/config/AmazonConfig.java
  src/main/java/umc/duckmelang/mongo/chatmessage/converter/ChatMessageConverter.java
  src/main/java/umc/duckmelang/mongo/chatmessage/domain/ChatMessage.java
  src/main/java/umc/duckmelang/mongo/chatmessage/domain/enums/MessageType.java
  src/main/java/umc/duckmelang/mongo/chatmessage/dto/ChatMessageRequestDto.java
  src/main/java/umc/duckmelang/mongo/chatmessage/dto/ChatMessageResponseDto.java
  src/main/java/umc/duckmelang/mongo/chatmessage/service/ChatMessageCommandServiceImpl.java
Labels: :sparkles: feature

#108 Refactor/#105 리뷰 작성 페이지 내 관련 정보 조회 API 개선
  src/main/java/umc/duckmelang/domain/review/controller/ReviewRestController.java
  src/main/java/umc/duckmelang/domain/review/repository/ReviewRepository.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewQueryService.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewQueryServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#104 Feature/#102 알림 읽음/삭제 & 알림 설정 관련 API 구현
  src/main/java/umc/duckmelang/domain/bookmark/service/BookmarkCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/service/member/MemberCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/notification/controller/NotificationRestController.java
  src/main/java/umc/duckmelang/domain/notification/converter/NotificationConverter.java
  src/main/java/umc/duckmelang/domain/notification/domain/Notification.java
  src/main/java/umc/duckmelang/domain/notification/dto/NotificationResponseDto.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationCommandService.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationQueryService.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/notificationsetting/controller/NotificationSettingRestController.java
  src/main/java/umc/duckmelang/domain/notificationsetting/converter/NotificationSettingConverter.java
  src/main/java/umc/duckmelang/domain/notificationsetting/domain/NotificationSetting.java
  src/main/java/umc/duckmelang/domain/notificationsetting/dto/NotificationSettingRequestDto.java
  src/main/java/umc/duckmelang/domain/notificationsetting/dto/NotificationSettingResponseDto.java
  src/main/java/umc/duckmelang/domain/notificationsetting/repository/NotificationSettingRepository.java
  src/main/java/umc/duckmelang/domain/notificationsetting/service/NotificationSettingCommandService.java
  src/main/java/umc/duckmelang/domain/notificationsetting/service/NotificationSettingCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/notificationsetting/service/NotificationSettingQueryService.java
  src/main/java/umc/duckmelang/domain/notificationsetting/service/NotificationSettingQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/NotificationException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/NotificationSettingException.java
  src/main/java/umc/duckmelang/global/validation/annotation/ExistNotification.java
  src/main/java/umc/duckmelang/global/validation/validator/NotificationExistValidator.java
Labels: :sparkles: feature

#110 feature/#88
  src/main/java/umc/duckmelang/global/websocket/WebSocketConfig.java
Labels: :recycle: refactor

#106 Feature/#89 : 채팅방 목록 조회
  src/main/java/umc/duckmelang/domain/chatroom/controller/ChatRoomRestController.java
  src/main/java/umc/duckmelang/domain/chatroom/converter/ChatRoomConverter.java
  src/main/java/umc/duckmelang/domain/chatroom/domain/ChatRoom.java
  src/main/java/umc/duckmelang/domain/chatroom/domain/enums/ChatRoomStatus.java
  src/main/java/umc/duckmelang/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/umc/duckmelang/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/umc/duckmelang/domain/chatroom/service/ChatRoomCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/chatroom/service/ChatRoomQueryService.java
  src/main/java/umc/duckmelang/domain/chatroom/service/ChatRoomQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/repository/MemberProfileImageRepository.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/domain/Post.java
  src/main/java/umc/duckmelang/domain/postimage/repository/PostImageRepository.java
  src/main/java/umc/duckmelang/domain/postimage/service/PostImageQueryServiceImpl.java
  src/main/java/umc/duckmelang/mongo/chatmessage/controller/ChatMessageWebSocketController.java
  src/main/java/umc/duckmelang/mongo/chatmessage/dto/ChatMessageRequestDto.java
  src/main/java/umc/duckmelang/mongo/chatmessage/dto/ChatMessageResponseDto.java
  src/main/java/umc/duckmelang/mongo/chatmessage/repository/ChatMessageRepository.java
  src/main/java/umc/duckmelang/mongo/chatmessage/service/ChatMessageCommandServiceImpl.java
  src/main/java/umc/duckmelang/mongo/chatmessage/service/ChatMessageQueryService.java
  src/main/java/umc/duckmelang/mongo/chatmessage/service/ChatMessageQueryServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#112 Refactor/#111
  src/main/java/umc/duckmelang/domain/landmine/converter/LandmineConverter.java
  src/main/java/umc/duckmelang/domain/landmine/dto/LandmineResponseDto.java
Labels: :recycle: refactor

#116 Feat: 닉네임 중복 확인 API 구현
  src/main/java/umc/duckmelang/domain/member/controller/MemberRestController.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberResponseDto.java
  src/main/java/umc/duckmelang/domain/member/service/member/MemberCommandService.java
  src/main/java/umc/duckmelang/domain/member/service/member/MemberCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageCommandServiceImpl.java
Labels: :sparkles: feature

#120 feature/#118 : 아이돌 전체 목록 조회 API 구현
  src/main/java/umc/duckmelang/domain/idolcategory/controller/IdolCategoryRestController.java
  src/main/java/umc/duckmelang/domain/idolcategory/service/IdolCategoryQueryService.java
  src/main/java/umc/duckmelang/domain/idolcategory/service/IdolCategoryQueryServiceImpl.java
Labels: :sparkles: feature

#117 Feature/#103
  src/main/java/umc/duckmelang/domain/auth/oauth/CustomOAuth2UserService.java
  src/main/java/umc/duckmelang/domain/auth/repository/AuthRepository.java
  src/main/java/umc/duckmelang/domain/bookmark/controller/BookmarkRestController.java
  src/main/java/umc/duckmelang/domain/landmine/controller/LandmineRestController.java
  src/main/java/umc/duckmelang/domain/member/controller/MyPageManagementRestController.java
  src/main/java/umc/duckmelang/domain/member/controller/MyPageRestController.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberFilterConverter.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberProfileConverter.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/domain/enums/MemberStatus.java
  src/main/java/umc/duckmelang/domain/member/dto/MyPageResponseDto.java
  src/main/java/umc/duckmelang/domain/member/repository/MemberRepository.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageCommandService.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageQueryService.java
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/memberidol/controller/MemberIdolRestController.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/controller/MemberProfileImageRestController.java
  src/main/java/umc/duckmelang/domain/post/controller/PostRestController.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/security/jwt/JwtUtil.java
  src/main/java/umc/duckmelang/global/security/user/CustomUserDetailsService.java
Labels: :sparkles: feature

#121 Feature/#114 동행 요청/동행 확정 알림 전송
  src/main/java/umc/duckmelang/domain/application/service/ApplicationCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/auth/oauth/CustomOAuth2UserService.java
  src/main/java/umc/duckmelang/domain/notification/service/NotificationHelper.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewCommandServiceImpl.java
Labels: :sparkles: feature

#128 Refactor: 후기 API score 타입 수정
  src/main/java/umc/duckmelang/domain/review/domain/Review.java
  src/main/java/umc/duckmelang/domain/review/dto/ReviewRequestDto.java
  src/main/java/umc/duckmelang/domain/review/dto/ReviewResponseDto.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewQueryServiceImpl.java
Labels: :recycle: refactor

#125 Feat: 게시글 상세 조회 API 채팅수 추가
  src/main/java/umc/duckmelang/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/umc/duckmelang/domain/chatroom/service/ChatRoomQueryService.java
  src/main/java/umc/duckmelang/domain/chatroom/service/ChatRoomQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/controller/PostRestController.java
  src/main/java/umc/duckmelang/domain/post/converter/PostConverter.java
  src/main/java/umc/duckmelang/domain/post/dto/PostResponseDto.java
  src/main/java/umc/duckmelang/domain/post/facade/PostFacadeService.java
Labels: :sparkles: feature

#126 Feat:채팅방 세부 조회 & 몽고db 타임존
  src/main/java/umc/duckmelang/domain/application/repository/ApplicationRepository.java
  src/main/java/umc/duckmelang/domain/chatroom/converter/ChatRoomConverter.java
  src/main/java/umc/duckmelang/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/umc/duckmelang/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/umc/duckmelang/domain/chatroom/service/ChatRoomQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/review/converter/ReviewConverter.java
  src/main/java/umc/duckmelang/domain/review/repository/ReviewRepository.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/ChatRoomException.java
  src/main/java/umc/duckmelang/global/config/MongoConfig.java
  src/main/java/umc/duckmelang/mongo/chatmessage/service/ChatMessageQueryService.java
Labels: :sparkles: feature

#134 Refactor: 게시글 상태변경 API requestParam추가
  src/main/java/umc/duckmelang/domain/post/controller/PostRestController.java
  src/main/java/umc/duckmelang/domain/post/domain/Post.java
  src/main/java/umc/duckmelang/domain/post/service/PostCommandService.java
  src/main/java/umc/duckmelang/domain/post/service/PostCommandServiceImpl.java
Labels: :recycle: refactor

#139 Refactor: 회원가입 response에 profileComplete 추가
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberSignUpDto.java
Labels: :recycle: refactor

#136 Feat: 검색기능에 필터링 설정 기능 구현
  src/main/java/umc/duckmelang/domain/member/service/mypage/MyPageCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/controller/PostRestController.java
  src/main/java/umc/duckmelang/domain/post/dto/PostRequestDto.java
  src/main/java/umc/duckmelang/domain/post/service/PostCommandService.java
  src/main/java/umc/duckmelang/domain/post/service/PostCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryServiceImpl.java
Labels: :sparkles: feature

#143 Fix: 회원가입에서 isProfileComplete 을 false로 변경
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
Labels: :recycle: refactor
