Repository Duckmelang/BE, pull requests merged in 2025-01, with the labels that each got.

#10 Feature/#8
  .gitignore
  src/main/java/umc/duckmelang/DuckmelangApplication.java
  src/main/java/umc/duckmelang/domain/application/domain/Application.java
  src/main/java/umc/duckmelang/domain/application/domain/enums/ApplicationStatus.java
  src/main/java/umc/duckmelang/domain/authprovider/domain/AuthProvider.java
  src/main/java/umc/duckmelang/domain/authprovider/enums/ProviderKind.java
  src/main/java/umc/duckmelang/domain/bookmark/domain/Bookmark.java
  src/main/java/umc/duckmelang/domain/eventcategory/domain/EventCategory.java
  src/main/java/umc/duckmelang/domain/idolcategory/domain/IdolCategory.java
  src/main/java/umc/duckmelang/domain/landmine/domain/Landmine.java
  src/main/java/umc/duckmelang/domain/materelationship/domain/MateRelationship.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/memberevent/domain/MemberEvent.java
  src/main/java/umc/duckmelang/domain/memberidol/domain/MemberIdol.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/domain/MemberProfileImage.java
  src/main/java/umc/duckmelang/domain/post/domain/Post.java
  src/main/java/umc/duckmelang/domain/postidol/domain/PostIdol.java
  src/main/java/umc/duckmelang/domain/postimage/domain/PostImage.java
  src/main/java/umc/duckmelang/domain/review/domain/Review.java
  src/main/java/umc/duckmelang/global/common/BaseEntity.java
  src/main/java/umc/duckmelang/global/config/SwaggerConfig.java
  src/main/resources/application-local.yml
  src/test/java/umc/duckmelang/domain/application/domain/ApplicationTest.java
  src/test/java/umc/duckmelang/domain/member/domain/MemberTest.java
  src/test/java/umc/duckmelang/domain/post/domain/PostTest.java
  src/test/java/umc/duckmelang/domain/review/domain/ReviewTest.java
Labels: :sparkles: feature

#14 Feature/#12
  build.gradle
  src/main/java/umc/duckmelang/domain/idolcategory/repository/IdolCategoryRepository.java
  src/main/java/umc/duckmelang/domain/idolcategory/service/IdolCategoryQueryService.java
  src/main/java/umc/duckmelang/domain/idolcategory/service/IdolCategoryQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/idolcategory/validation/annotation/ExistIdol.java
  src/main/java/umc/duckmelang/domain/idolcategory/validation/validator/IdolExistValidator.java
  src/main/java/umc/duckmelang/domain/post/controller/PostController.java
  src/main/java/umc/duckmelang/domain/post/converter/PostConverter.java
  src/main/java/umc/duckmelang/domain/post/dto/PostResponseDto.java
  src/main/java/umc/duckmelang/domain/post/repository/PostRepository.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryService.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryServiceImpl.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/resources/application-local.yml
Labels: :sparkles: feature

#16 Feature/#13
  .gitignore
  src/main/java/umc/duckmelang/DuckmelangApplication.java
  src/main/java/umc/duckmelang/domain/application/controller/ApplicationRestController.java
  src/main/java/umc/duckmelang/domain/application/converter/ApplicationConverter.java
  src/main/java/umc/duckmelang/domain/application/domain/Application.java
  src/main/java/umc/duckmelang/domain/application/dto/ApplicationRequestDto.java
  src/main/java/umc/duckmelang/domain/application/dto/ApplicationResponseDto.java
  src/main/java/umc/duckmelang/domain/application/dto/ReceivedApplicationDto.java
  src/main/java/umc/duckmelang/domain/application/dto/SentApplicationDto.java
  src/main/java/umc/duckmelang/domain/application/repository/ApplicationRepository.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationCommandService.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryService.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/application/validation/annotation/ExistApplication.java
  src/main/java/umc/duckmelang/domain/application/validation/validator/ApplicationExistValidator.java
  src/main/java/umc/duckmelang/domain/materelationship/repository/MateRelationshipRepository.java
  src/main/java/umc/duckmelang/domain/member/repository/MemberRepository.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/handler/ApplicationHandler.java
  src/main/java/umc/duckmelang/global/apipayload/exception/handler/MemberHandler.java
  src/main/resources/application-local.yml
  src/test/java/umc/duckmelang/domain/application/service/ApplicationCommandServiceImplTest.java
  src/test/java/umc/duckmelang/domain/application/service/ApplicationQueryServiceImplTest.java
Labels: :sparkles: feature

#23 Feature/#18
  src/main/java/umc/duckmelang/domain/bookmark/controller/BookmarkController.java
  src/main/java/umc/duckmelang/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/umc/duckmelang/domain/bookmark/service/BookmarkQueryService.java
  src/main/java/umc/duckmelang/domain/bookmark/service/BookmarkQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/controller/PostController.java
  src/main/java/umc/duckmelang/domain/post/converter/PostConverter.java
  src/main/java/umc/duckmelang/domain/post/domain/Post.java
  src/main/java/umc/duckmelang/domain/post/dto/PostRequestDto.java
  src/main/java/umc/duckmelang/domain/post/dto/PostResponseDto.java
  src/main/java/umc/duckmelang/domain/post/repository/PostRepository.java
  src/main/java/umc/duckmelang/domain/post/service/PostCommandService.java
  src/main/java/umc/duckmelang/domain/post/service/PostCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryService.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/validation/annotation/ExistPost.java
  src/main/java/umc/duckmelang/domain/post/validation/annotation/ValidPageNumber.java
  src/main/java/umc/duckmelang/domain/post/validation/validator/PageNumberValidator.java
  src/main/java/umc/duckmelang/domain/post/validation/validator/PostExistValidator.java
  src/main/java/umc/duckmelang/global/annotations/CommonApiResponses.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
Labels: :sparkles: feature

#25 Feature/#24
  src/main/java/umc/duckmelang/domain/application/domain/Application.java
  src/main/java/umc/duckmelang/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/umc/duckmelang/domain/member/service/MemberQueryService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/validation/annotation/ExistMember.java
  src/main/java/umc/duckmelang/domain/member/validation/validator/MemberExistValidator.java
  src/main/java/umc/duckmelang/domain/post/dto/PostRequestDto.java
  src/main/java/umc/duckmelang/domain/review/controller/ReviewController.java
  src/main/java/umc/duckmelang/domain/review/converter/ReviewConverter.java
  src/main/java/umc/duckmelang/domain/review/domain/Review.java
  src/main/java/umc/duckmelang/domain/review/dto/ReviewRequestDto.java
  src/main/java/umc/duckmelang/domain/review/dto/ReviewResponseDto.java
  src/main/java/umc/duckmelang/domain/review/repository/ReviewRepository.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewCommandService.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewQueryService.java
  src/main/java/umc/duckmelang/domain/review/service/ReviewQueryServiceImpl.java
Labels: :sparkles: feature

#15 feature/#9
  build.gradle
  src/main/java/umc/duckmelang/domain/application/service/ApplicationCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/auth/controller/AuthController.java
  src/main/java/umc/duckmelang/domain/auth/domain/Auth.java
  src/main/java/umc/duckmelang/domain/auth/dto/AuthRequestDto.java
  src/main/java/umc/duckmelang/domain/auth/dto/AuthResponseDto.java
  src/main/java/umc/duckmelang/domain/auth/enums/ProviderKind.java
  src/main/java/umc/duckmelang/domain/auth/repository/AuthRepository.java
  src/main/java/umc/duckmelang/domain/auth/service/AuthService.java
  src/main/java/umc/duckmelang/domain/authprovider/enums/ProviderKind.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberRequestDto.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberResponseDto.java
  src/main/java/umc/duckmelang/domain/member/repository/MemberRepository.java
  src/main/java/umc/duckmelang/global/apipayload/ApiResponse.java
  src/main/java/umc/duckmelang/global/apipayload/ExceptionAdvice.java
  src/main/java/umc/duckmelang/global/apipayload/code/BaseErrorCode.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/ApplicationException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/AuthException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/EventCategoryException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/GeneralException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/IdolCategoryException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/LandmineException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/MemberException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/TempException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/TokenException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/handler/ApplicationHandler.java
  src/main/java/umc/duckmelang/global/apipayload/exception/handler/MemberHandler.java
  src/main/java/umc/duckmelang/global/apipayload/exception/handler/TempHandler.java
  src/main/java/umc/duckmelang/global/config/SwaggerConfig.java
  src/main/java/umc/duckmelang/global/redis/RedisConfig.java
  src/main/java/umc/duckmelang/global/redis/blacklist/BlacklistService.java
  src/main/java/umc/duckmelang/global/redis/blacklist/BlacklistServiceImpl.java
  src/main/java/umc/duckmelang/global/redis/refreshtoken/RefreshToken.java
  src/main/java/umc/duckmelang/global/redis/refreshtoken/RefreshTokenRepository.java
  src/main/java/umc/duckmelang/global/redis/refreshtoken/RefreshTokenService.java
  src/main/java/umc/duckmelang/global/redis/refreshtoken/RefreshTokenServiceImpl.java
  src/main/java/umc/duckmelang/global/security/config/SecurityConfig.java
  src/main/java/umc/duckmelang/global/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/umc/duckmelang/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/umc/duckmelang/global/security/jwt/JwtTokenProvider.java
  src/main/java/umc/duckmelang/global/security/jwt/JwtUtil.java
  src/main/java/umc/duckmelang/global/security/user/CustomUserDetails.java
  src/main/java/umc/duckmelang/global/security/user/CustomUserDetailsService.java
  src/main/java/umc/duckmelang/global/temp/controller/TempRestController.java
  src/main/java/umc/duckmelang/global/temp/service/TempQueryServiceImpl.java
  src/test/java/umc/duckmelang/domain/application/service/ApplicationCommandServiceImplTest.java
Labels: :sparkles: feature

#28 Feature/#20
  src/main/java/umc/duckmelang/domain/application/repository/ApplicationRepository.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryService.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/controller/MyPageController.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberRequestDto.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberResponseDto.java
  src/main/java/umc/duckmelang/domain/member/facade/ProfileFacadeService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/service/MemberQueryService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/controller/MemberProfileImageController.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/converter/MemberProfileImageConverter.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/domain/MemberProfileImage.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageRequestDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageResponseDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/repository/MemberProfileImageRepository.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandService.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryService.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/repository/PostRepository.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryService.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryServiceImpl.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/handler/MemberProfileImageHandler.java
  src/test/java/umc/duckmelang/domain/member/service/MemberQueryServiceTest.java
  src/test/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryServiceTest.java
Labels: :sparkles: feature

#22 Feature/#19
  src/main/java/umc/duckmelang/domain/application/controller/ApplicationRestController.java
  src/main/java/umc/duckmelang/domain/application/repository/ApplicationRepository.java
  src/main/java/umc/duckmelang/domain/application/service/ApplicationQueryService.java
  src/main/java/umc/duckmelang/domain/application/validation/annotation/ExistsApplication.java
  src/main/java/umc/duckmelang/domain/application/validation/validator/ApplicationExistsValidator.java
  src/main/java/umc/duckmelang/domain/member/controller/MyPageController.java
  src/main/java/umc/duckmelang/domain/member/controller/ProfileRestController.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberResponseDto.java
  src/main/java/umc/duckmelang/domain/member/facade/ProfileFacadeService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberQueryService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/validation/annotation/ExistsMember.java
  src/main/java/umc/duckmelang/domain/member/validation/validator/MemberExistsValidator.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/converter/MemberProfileImageConverter.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageResponseDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/repository/MemberProfileImageRepository.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/post/repository/PostRepository.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryService.java
  src/main/java/umc/duckmelang/domain/post/service/PostQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/postimage/converter/PostImageConverter.java
  src/main/java/umc/duckmelang/domain/postimage/dto/PostImageResponseDto.java
  src/main/java/umc/duckmelang/domain/postimage/dto/PostThumbnailResponseDto.java
  src/main/java/umc/duckmelang/domain/postimage/repository/PostImageRepository.java
  src/main/java/umc/duckmelang/domain/postimage/service/PostImageQueryService.java
  src/main/java/umc/duckmelang/domain/postimage/service/PostImageQueryServiceImpl.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/handler/MemberProfileImageException.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#36 Feature/#34
  src/main/java/umc/duckmelang/domain/member/controller/MemberController.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberRequestDto.java
  src/main/java/umc/duckmelang/domain/member/facade/ProfileFacadeService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageRequestDto.java
  src/test/java/umc/duckmelang/domain/member/service/MemberCommandServiceTest.java
Labels: :bug: bug

#43 Feature/#41
  src/main/java/umc/duckmelang/domain/memberprofileimage/converter/MemberProfileImageConverter.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/domain/MemberProfileImage.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageRequestDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandServiceImpl.java
Labels: :bug: bug, :recycle: refactor

#44 Feature/#42
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryServiceImpl.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/apipayload/exception/TempException.java
  src/main/java/umc/duckmelang/global/apipayload/exception/handler/MemberProfileImageException.java
  src/main/java/umc/duckmelang/global/temp/controller/TempRestController.java
  src/main/java/umc/duckmelang/global/temp/converter/TempConverter.java
  src/main/java/umc/duckmelang/global/temp/dto/TempRequest.java
  src/main/java/umc/duckmelang/global/temp/dto/TempResponse.java
  src/main/java/umc/duckmelang/global/temp/service/TempCommandService.java
  src/main/java/umc/duckmelang/global/temp/service/TempCommandServiceImpl.java
  src/main/java/umc/duckmelang/global/temp/service/TempQueryService.java
  src/main/java/umc/duckmelang/global/temp/service/TempQueryServiceImpl.java
  src/test/java/umc/duckmelang/domain/application/service/ApplicationCommandServiceImplTest.java
  src/test/java/umc/duckmelang/domain/member/controller/MemberControllerTest.java
  src/test/java/umc/duckmelang/domain/member/service/MemberCommandServiceTest.java
  src/test/java/umc/duckmelang/domain/member/service/MemberQueryServiceTest.java
  src/test/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryServiceTest.java
Labels: :recycle: refactor

#29 Feature/#21
  .gitignore
  build.gradle
  src/main/java/umc/duckmelang/domain/application/repository/ApplicationRepository.java
  src/main/java/umc/duckmelang/domain/auth/controller/AuthController.java
  src/main/java/umc/duckmelang/domain/auth/dto/AuthResponseDto.java
  src/main/java/umc/duckmelang/domain/auth/oauth/CustomOAuth2UserService.java
  src/main/java/umc/duckmelang/domain/auth/oauth/OAuth2LoginSuccessHandler.java
  src/main/java/umc/duckmelang/domain/auth/oauth/OAuthAttributes.java
  src/main/java/umc/duckmelang/domain/auth/repository/AuthRepository.java
  src/main/java/umc/duckmelang/domain/auth/service/AuthService.java
  src/main/java/umc/duckmelang/domain/member/controller/MemberController.java
  src/main/java/umc/duckmelang/domain/member/controller/MyPageController.java
  src/main/java/umc/duckmelang/domain/member/converter/MemberConverter.java
  src/main/java/umc/duckmelang/domain/member/domain/Member.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberRequestDto.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberResponseDto.java
  src/main/java/umc/duckmelang/domain/member/dto/MemberSignUpDto.java
  src/main/java/umc/duckmelang/domain/member/facade/ProfileFacadeService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandService.java
  src/main/java/umc/duckmelang/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/service/MemberQueryServiceImpl.java
  src/main/java/umc/duckmelang/domain/member/validation/validator/MemberExistValidator.java
  src/main/java/umc/duckmelang/domain/post/converter/PostConverter.java
  src/main/java/umc/duckmelang/domain/post/dto/PostResponseDto.java
  src/main/java/umc/duckmelang/global/apipayload/code/status/ErrorStatus.java
  src/main/java/umc/duckmelang/global/redis/refreshtoken/RefreshTokenServiceImpl.java
  src/main/java/umc/duckmelang/global/security/config/SecurityConfig.java
  src/main/java/umc/duckmelang/global/security/jwt/JwtTokenProvider.java
  src/test/java/umc/duckmelang/domain/member/service/MemberCommandServiceTest.java
Labels: :sparkles: feature

#35 Feature/#31
  build.gradle
  src/main/java/umc/duckmelang/domain/auth/sms/SmsCertificationUtil.java
  src/main/java/umc/duckmelang/domain/auth/sms/SmsController.java
  src/main/java/umc/duckmelang/domain/auth/sms/SmsRepository.java
  src/main/java/umc/duckmelang/domain/auth/sms/SmsService.java
  src/main/java/umc/duckmelang/domain/auth/sms/SmsServiceImpl.java
  src/main/java/umc/duckmelang/domain/auth/sms/dto/SmsRequestDto.java
  src/main/java/umc/duckmelang/domain/auth/sms/dto/SmsVerifyDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/controller/MemberProfileImageController.java
Labels: :sparkles: feature

#48 Feature/#46
  src/main/java/umc/duckmelang/domain/member/controller/ProfileRestController.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/controller/MemberProfileImageController.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/converter/MemberProfileImageConverter.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageResponseDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/repository/MemberProfileImageRepository.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryService.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageQueryServiceImpl.java
  src/test/java/umc/duckmelang/domain/application/domain/ApplicationTest.java
  src/test/java/umc/duckmelang/domain/application/service/ApplicationCommandServiceImplTest.java
  src/test/java/umc/duckmelang/domain/application/service/ApplicationQueryServiceImplTest.java
  src/test/java/umc/duckmelang/domain/member/domain/MemberTest.java
  src/test/java/umc/duckmelang/domain/member/service/MemberCommandServiceTest.java
  src/test/java/umc/duckmelang/domain/post/domain/PostTest.java
  src/test/java/umc/duckmelang/domain/review/domain/ReviewTest.java
Labels: duplicate

#50 Feature/#49
  src/main/java/umc/duckmelang/domain/memberprofileimage/dto/MemberProfileImageRequestDto.java
  src/main/java/umc/duckmelang/domain/memberprofileimage/service/MemberProfileImageCommandServiceImpl.java
Labels: :bug: bug

#52 Feature/#51
  .gitignore
  src/main/java/umc/duckmelang/global/security/config/SecurityConfig.java
Labels: :sparkles: feature

#57 bug: GitHub Actions 에러
  .github/workflows/dev_deploy.yml
Labels: :bug: bug
